/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IHeroiconsArrowUp: typeof import('~icons/heroicons/arrow-up')['default']
    IHeroiconsArrowUp20Solid: typeof import('~icons/heroicons/arrow-up20-solid')['default']
    IHeroiconsClock: typeof import('~icons/heroicons/clock')['default']
    IHeroiconsClockSolid: typeof import('~icons/heroicons/clock-solid')['default']
    IHeroiconsSArrowUp: typeof import('~icons/heroicons/s-arrow-up')['default']
    IHeroiconsWatch: typeof import('~icons/heroicons/watch')['default']
    IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
